### ISSUE TITLE
リソース設計

### ISSUE THREAD

**Issue by maimux2x** [maimux2x/subsc.mine#13]
![Image](https://user-images.githubusercontent.com/76797372/232178895-322e1e23-6027-436c-b7ee-487dd95cc86c.jpeg)

**Comment by maimux2x** [comment]
## リソース設計
| Method | Path | Description |
|---|---|---|
| GET | / | トップ画面を表示（ログインしていればツリー一覧を、ログインしていなければサービスLPを表示する）|
| GET | /auth/:provider/callback | OAuth 2.0によるログイン処理、ユーザー作成処理 |
| DELETE | /logout | ログアウトの実行 |
| GET | /subscriptions | 登録したサブスクの一覧画面 |
| POST | /subscriptions/new | サブスクの新規登録画面 |
| PATCH | /subscriptions/:id/edit | サブスクの編集画面 |
| DELETE | /subscriptions/:id | サブスクの削除 |
| PATCH | /subscriptions/:id | サブスク利用状況のステータス更新 |
| DELETE | /retirement | 退会処理 |

- フレームワークはバックエンドはRails7、フロントはslimとVue.jsの組み合わせで作成予定です。
　- サブスク利用状況のステータス更新と退会処理の部分をSPAでVue.jsを利用して作成します。（モーダルでの処理） 
- ログインにはGoogleログインを利用します。

**Comment by kfukai23** [comment]
よさそうです〜！
