### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by maimux2x** [maimux2x/subsc.mine#6]

**Comment by maimux2x** [comment]
![Image](https://user-images.githubusercontent.com/76797372/224548696-e50df59e-9d5c-49ae-9880-69156bfcd135.jpg)

## Users
| No | 論理名称 | 物理名称 | データ型 | PK | UQ | NN| 備考 |
|---|---|---|---|---|---|---|---|
| 1 | id | id | integer| ○ | ○ | ○ | |
| 2 | provider | provider | string | | | ○ | |
| 3 | uid | uid | string | | ○ | ○ | |

## Subscriptions
| No | 論理名称 | 物理名称 | データ型 | PK | FK | UQ | NN| 備考 |
|---|---|---|---|---|---|---|---|---|
| 1 | id | id | integer| ○ | | ○ | ○ | |
| 2 | user_id | user_id | integer | | ○ | ○ | ○ | |
| 3 | サービス名 | name | string | | | | ○ | |
| 4 | お支払日 | payment_date | date | | | | ○ | |
| 5 | 次回お支払日 | next_payment_date | date | | | | ○ | |
| 6 | お支払い金額 | subscription_fee | integer | | | | ○ | |
| 7 | マイアカウントURL | my_account_url | string | | | | | |
| 8 | 購読可否 | subscribed | boolean | | | | ○ | true: 購読中 / false:休止中 |
| 9| 周期 | cycle integer | | | | | ○ | enmu { one_month : 1, two_month : 2, three_month : 3, six_month : 4, twelve_month : 5 }

**Comment by kfukai23** [comment]
ペーパープロトタイピングなどには一通り目を通しましたが、完全にサービスのことを理解できてはいないと思うので、何か誤解などありましたらすみませんが補足お願いします〜:pray:

> 次回お支払日 | next_payment_date 

このカラムってどういう風に使うイメージですか？:eyes:
payment_date に cycle をかけて算出するのかな〜と推測したのですが、それなら値をDBにしまっておく必要はないかなぁと思った感じです。

> お支払い金額 | subscription_fee

テーブル名が subscriptions なので、シンプルに fee でよさそうな気がします〜

> 購読可否 | subscribed

細かいですが「購読有無」ですかね〜:eyes:
あと、DBそのものというよりはRailsの世界の話になってしまうのですが、ActiveRecord は Boolean 型のカラムに対して真偽値を返すメソッドを自動で追加してくれるので、そのメソッド名として自然なカラム名にしておくと楽です（Rails側でDBのカラム名と違う名前をつけることもたぶんできると思うのですが、今回のケースでは分ける意味もないと思うので）。 
具体的にはこういうことです。

```ruby
@subscription = current_user.subscriptions.find(params[:id])
# @subscription.subscribed? とするか、@subscription.ongoing? とするか、はたまた別の名前にするか...
```

> 周期 | cycle

enumでもまあいいとは思うんですが、six_month, twelve_month はマッピングされる数値が月の数と合わないので個人的にはちょっとだけ違和感あるかもです:thinking:
シンプルに月の数を数値で持つようにしてもやりたいことはできそうで、かつ柔軟かなと。あまりないかもしれないですが1, 2, 3, 6, 12ヶ月以外の周期が必要になっても追加が容易ですので（というかenumだと大変そう）。

**Comment by maimux2x** [comment]
@kfukai23 さん
レビューありがとうございます！

以下、いただいたフィードバックに対する回答になります！

> このカラムってどういう風に使うイメージですか？👀
payment_date に cycle をかけて算出するのかな〜と推測したのですが、それなら値をDBにしまっておく必要はないかなぁと思った感じです。

`next_payment_date` を加えた理由は以下になります。

- サブスクマスターのサブスクリプション一覧画面では「今月のお支払い日」「次月のお支払い日」を表示させたい。

`next_payment_date` はユーザーが新規サブスクリプションを登録する際に「今月のお支払い日」「周期」を入力してもらい、保存時にその二つのデータから自動で計算してDBに保存する流れを考えています。

また、この保存時にGoogleカレンダーに対して「今月のお支払い日」「次月のお支払い日」を連携させます。

新規登録後は翌月月初の0:10(仮）などにスケジューラーで

- 「今月のお支払い日」を前月に「次月のお支払い日」だったデータに更新
- 「今月のお支払い日」「周期」から新しい「次月のお支払い日」を算出
- Googleカレンダーも更新

という処理を考えています。

> テーブル名が subscriptions なので、シンプルに fee でよさそうな気がします〜

こちらは `fee` に修正いたします！

> 細かいですが「購読有無」ですかね〜

こちらは

- 論理名称：購読有無
- 物理名称：`is_subscribed?` 

にしてみました。

> シンプルに月の数を数値で持つようにしてもやりたいことはできそうで、かつ柔軟かなと。あまりないかもしれないですが1, 2, 3, 6, 12ヶ月以外の周期が必要になっても追加が容易ですので（というかenumだと大変そう）。

こちらは `cyclels` としてテーブルを分割してみました。

修正後のER図と詳細は以下になります。

![My First Board (2)](https://user-images.githubusercontent.com/76797372/226158911-635285c3-2dbc-4a3e-8690-b25810be0ee7.jpg)

## Subscriptions
| No | 論理名称 | 物理名称 | データ型 | PK | FK | UQ | NN| 備考 |
|---|---|---|---|---|---|---|---|---|
| 1 | id | id | integer| ○ | | ○ | ○ | |
| 2 | user_id | user_id | integer | | ○ | ○ | ○ | |
| 3 | cycle_id | cycle_id | integer | | ○ | ○ | ○ | |
| 4 | サービス名 | name | string | | | | ○ | |
| 5 | お支払日 | payment_date | date | | | | ○ | |
| 6 | 次回お支払日 | next_payment_date | date | | | | ○ | |
| 7 | お支払い金額 | fee | integer | | | | ○ | |
| 8 | マイアカウントURL | my_account_url | string | | | | | |
| 9 | 購読有無 | is_subscribed? | boolean | | | | ○ | true: 購読中 / false:休止中 |

## Cycles
| No | 論理名称 | 物理名称 | データ型 | PK | UQ | NN| 備考 |
|---|---|---|---|---|---|---|---|---|
| 1 | id | id | integer| ○ | ○ | ○ | |
| 2 | 周期 | term | string |  | ○ | ○ | |

改めてご確認の程よろしくお願いいたします🙏

**Comment by kfukai23** [comment]
> next_payment_date を加えた理由は以下になります。...

なるほど、用途は把握しました。その上で、やはりDBに値を持っておくべき理由があまり見当たらなかったのですが、そのあたりはどのように考えていますか？:eyes:

> こちらは cyclels としてテーブルを分割してみました。

僕のコメントに対する回答としてそのような修正を加えようと考えた理由を教えていただきたいです:pray: 
「enumで固定しないようにする」という面ではコメントに対する筋が通っていると思いますが、なぜわざわざテーブルを分けるのか？「数値で持つのがよいのでは」というコメントを受けてどのように考えたのか？が書かれていない & 変更内容からはちょっと読み取れないので。
また、テーブルを分けるとしても文字列型で持つようにした理由も知りたいです。

> 物理名称：is_subscribed?

Rubyのスタイルガイドでは `is_` という接頭辞は避けるように書かれていますね。RuboCopでも警告されると思います。
https://github.com/rubocop/ruby-style-guide#predicate-methods-prefix

**Comment by maimux2x** [comment]
@kfukai23 さん
改めてレビューいただき、ありがとうございます！
修正前にいただいたレビューへのご返信と質問をさせていただけると幸いです🙇🏻‍♀️

> なるほど、用途は把握しました。その上で、やはりDBに値を持っておくべき理由があまり見当たらなかったのですが、そのあたりはどのように考えていますか？👀

こちらについて再度考えてみました。
例えば

```
payment_date = 2023-03-25 # 日付の表記はダミー

next_payment_date = payment_date + 30 # 周期の計算も実際想定しているものとは異なる

# => next_payment_date は2023-04-25 になる
```

とした場合に、変数として値を保持するのみで、それをDBに保存する必要はないという理解でよろしいでしょうか？
その場合は確かに「今月のお支払い日」のみがDBに保持されていれば計算処理は可能なため「次月のお支払い日」はDBに不要だなと思いました。

> 「enumで固定しないようにする」という面ではコメントに対する筋が通っていると思いますが、なぜわざわざテーブルを分けるのか？「数値で持つのがよいのでは」というコメントを受けてどのように考えたのか？が書かれていない & 変更内容からはちょっと読み取れないので。

こちらは以下の記事を読んでenumを使用しない場合はテーブルを分割した方が良いと紹介されていたのを安易に取り入れてしまいました・・・

- [【Rails】enumのデメリットについて考える](https://zenn.dev/shuhei_takada/articles/be002838ae379a)

ここで質問になるのですが、「数値で持つ」場合、Subscriptionsテーブルでどのように複数の周期の値を持つのかがイメージが持てておりません🙇🏻‍♀️

実装のイメージとしては一つのサブスクは一つの周期を持つことを想定しており、サブスクの新規登録時にDB側に保持されている複数の周期の中から任意の周期を一つプルダウンから選択させたいと考えております。
そのため、上記記事を参考にし、Subscriptionsテーブルから周期を別テーブルとして切り出すことでやりたいことが可能になるのではと考えました。

この点について認識の誤りがありましたら改めて詳細をお伺いできますと幸いです。

> また、テーブルを分けるとしても文字列型で持つようにした理由も知りたいです。

こちらはフロントに出力する際に `nヶ月` という単位で出したかったため、`String` にしてしまったのですが、DB側では `Integer` で数値だけ持ち、フロントの実装時に単位と合わせれば問題ないですね・・・。
修正いたします！

> Rubyのスタイルガイドでは is_ という接頭辞は避けるように書かれていますね。RuboCopでも警告されると思います。

これは把握できていませんでした・・・共有いただき、ありがとうございます！
`subscribed?` という物理名称にしようと思います！

うまく説明ができていない点もあると思われ恐縮ですが、改めてご確認の程よろしくお願いいたします🙏

**Comment by maimux2x** [comment]
@kfukai23 さん
ありがとうございます！
`cycle` を数値で持つという意図をようやく理解しました！
ずっとDB側で選択可能な周期を値として持っていないとと思っていたのですが、必ずしもその必要はないということですね。

修正を反映させたため、あらためてご確認の程よろしくお願いいたします🙏

![My First Board (3)](https://user-images.githubusercontent.com/76797372/227559254-9089661b-d493-4764-9294-0906dec52487.jpg)

## Users
| No | 論理名称 | 物理名称 | データ型 | PK | UQ | NN| 備考 |
|---|---|---|---|---|---|---|---|
| 1 | id | id | integer| ○ | ○ | ○ | |
| 2 | メールアドレス | email | string | | ○ | ○ | |


## Subscriptions
| No | 論理名称 | 物理名称 | データ型 | PK | FK | UQ | NN| 備考 |
|---|---|---|---|---|---|---|---|---|
| 1 | id | id | integer| ○ | | ○ | ○ | |
| 2 | user_id | user_id | integer | | ○ | ○ | ○ | |
| 3 | サービス名 | name | string | | | | ○ | |
| 4 | お支払日 | payment_date | date | | | | ○ | |
| 5 | お支払い金額 | subscription_fee | integer | | | | ○ | |
| 6 | マイアカウントURL | my_account_url | string | | | | | |
| 7 | 購読可否 | subscribed | boolean? | | | | ○ | true: 購読中 / false:休止中 |
| 8 | 周期 | cycle  | integer | | | | ○ | |

**Comment by kfukai23** [comment]
よさそうです！修正ありがとうございます〜:+1:
